# Imported sources enabled by the Keil RkNano A_CORE target.
AP_SRCS := \
  firmware/rockchip/driver/PMU/PMU.c \
  firmware/rockchip/driver/ADC/Adc.c \
  firmware/rockchip/driver/DMA/Dma.c \
  firmware/rockchip/driver/I2C/i2c.c \
  firmware/rockchip/driver/IIS/I2s.c \
  firmware/rockchip/driver/GPIO/gpio.c \
  firmware/rockchip/driver/SPI/Spi.c \
  firmware/rockchip/driver/SYSTICK/systick.c \
  firmware/rockchip/driver/TIMER/timer.c \
  firmware/rockchip/driver/AD_KEY/AD_Key.c \
  firmware/rockchip/driver/UART/uart.c \
  firmware/rockchip/driver/DAC/rockcodec/rockcodec.c \
  firmware/rockchip/driver/RadioDriver/QN8035/hw_qn8035.c \
  firmware/rockchip/driver/RadioDriver/FM5807/hw_fm5807.c \
  firmware/rockchip/driver/LCD/Lcd_S6B0724_96x64.c \
  firmware/rockchip/driver/DAC/wm8987/hw_wm8987.c \
  firmware/rockchip/driver/LCD/ST7735Driver.c \
  firmware/rockchip/driver/vop/vop.c \
  firmware/rockchip/driver/mailbox/mailbox.c \
  firmware/rockchip/driver/CRU/cru.c \
  firmware/rockchip/driver/GRF/grf.c \
  firmware/rockchip/driver/PWM/pwm.c \
  firmware/rockchip/driver/WatchDog/WatchDog.c \
  firmware/rockchip/driver/DAC/ALC5633/Hw_alc5633.c \
  firmware/rockchip/driver/pmc/pmc.c \
  firmware/rockchip/driver/PVTM/pvtm.c \
  firmware/rockchip/driver/vop/yuv2rgb.c \
  firmware/rockchip/driver/LCD/ST7735S_Driver_1.0.c \
  firmware/rockchip/driver/BB/BBSystem.c \
  firmware/rockchip/driver/USB/host/USB_DWCHost.c \
  firmware/rockchip/driver/USB/host/usb_msc_host.c \
  firmware/rockchip/system/debug/Debug.c \
  firmware/rockchip/app_main.c \
  firmware/rockchip/system/sysservice/Hook.c \
  firmware/rockchip/display/LcdCharLib.c \
  firmware/rockchip/display/LcdChar.c \
  firmware/rockchip/display/LcdImage.c \
  firmware/rockchip/display/LcdInterface.c \
  firmware/rockchip/system/sysservice/Delay.c \
  firmware/rockchip/system/sysservice/Backlight.c \
  firmware/rockchip/system/sysservice/battery.c \
  firmware/rockchip/system/sysservice/Service.c \
  firmware/rockchip/system/os/interrupt.c \
  firmware/rockchip/system/fileseek/SysFindFile.c \
  firmware/rockchip/system/os/SysTickHandler.c \
  firmware/rockchip/system/sysservice/UsbAdapterProbe.c \
  firmware/rockchip/display/8859_x_12_add9.c \
  firmware/rockchip/display/8859_x_12_Width_add9.c \
  firmware/rockchip/display/8859_x_Table_add9.c \
  firmware/rockchip/display/COMP_NewJ_12_CJK.c \
  firmware/rockchip/display/COMP_NewJ_12_JKC.c \
  firmware/rockchip/display/COMP_NewJ_tbl.c \
  firmware/rockchip/display/FontLib.c \
  firmware/rockchip/display/getThaiChar.c \
  firmware/rockchip/display/THAI12.c \
  firmware/rockchip/system/sysservice/PowerManager.c \
  firmware/rockchip/system/os/Msg.c \
  firmware/rockchip/system/os/Win.c \
  firmware/rockchip/system/os/Thread.c \
  firmware/rockchip/system/os/Task.c \
  firmware/rockchip/system/os/OsHook.c \
  firmware/rockchip/system/module_overlay/ModuleOverlay.c \
  firmware/rockchip/system/module_overlay/SysReservedOperation.c \
  firmware/rockchip/fwupdate/FwUpdate.c \
  firmware/rockchip/plug/bsp/BSP.c \
  firmware/rockchip/plug/shell/ShellTask.c \
  firmware/rockchip/plug/uartdevice/UartDevice.c \
  firmware/rockchip/plug/spidevice/SPIDevice.c \
  firmware/rockchip/driver/MemDev/MemDev.c \
  firmware/rockchip/driver/MemDev/SD_MMC/SDM.c \
  firmware/rockchip/driver/MemDev/SD_MMC/eMMC.c \
  firmware/rockchip/driver/MemDev/SD_MMC/MMC.c \
  firmware/rockchip/driver/MemDev/SD_MMC/SD.c \
  firmware/rockchip/driver/MemDev/SD_MMC/SDCtrl.c \
  firmware/rockchip/driver/MemDev/SD_MMC/SDAdapt.c \
  firmware/rockchip/driver/MemDev/SPIFlash/SPIFlash.c \
  firmware/rockchip/driver/MemDev/SPIFlash/SFC.c \
  firmware/rockchip/driver/MemDev/SPIFlash/SFNand.c \
  firmware/rockchip/driver/MemDev/SPIFlash/SFNor.c \
  firmware/rockchip/filesys/Decode.c \
  firmware/rockchip/filesys/nFAT.c \
  firmware/rockchip/filesys/fat.c \
  firmware/rockchip/filesys/FDT.c \
  firmware/rockchip/filesys/dir.c \
  firmware/rockchip/filesys/file.c \
  firmware/rockchip/filesys/FileSeek.c \
  firmware/rockchip/ui/dialog/DialogBox.c \
  firmware/rockchip/ui/dialog/MessageBox.c \
  firmware/rockchip/ui/dialog/LowPower.c \
  firmware/rockchip/ui/dialog/Hold.c \
  firmware/rockchip/ui/dialog/PowerOn_Off.c \
  firmware/rockchip/ui/MainMenu/MainMenu.c \
  firmware/rockchip/ui/MainMenu/MainMenuInterface.c \
  firmware/rockchip/ui/MusicWin/MusicWin.c \
  firmware/rockchip/ui/MusicWin/MusicWinInterface.c \
  firmware/rockchip/ui/RadioWin/RadioWin.c \
  firmware/rockchip/ui/RadioWin/RadioWinInterface.c \
  firmware/rockchip/ui/RadioWin/RadioSubWin/RadioSubFreqWin.c \
  firmware/rockchip/ui/RadioWin/RadioSubWin/RadioSubFuncWin.c \
  firmware/rockchip/ui/RadioWin/RadioSubWin/RadioSubWinInterface.c \
  firmware/rockchip/ui/RecordWin/RecordWin.c \
  firmware/rockchip/ui/RecordWin/RecordWinInterface.c \
  firmware/rockchip/ui/Browser/BrowserUI/BrowserUI.c \
  firmware/rockchip/ui/Browser/BroCore/BroCore.c \
  firmware/rockchip/ui/SetMenu/SetMenu.c \
  firmware/rockchip/ui/SetMenu/SystemSet.c \
  firmware/rockchip/ui/SetMenu/SetCommon.c \
  firmware/rockchip/ui/SetMenu/SetMenuInterface.c \
  firmware/rockchip/ui/SetMenu/SetMusic.c \
  firmware/rockchip/ui/SetMenu/SetRadio.c \
  firmware/rockchip/ui/SetMenu/SetRecord.c \
  firmware/rockchip/ui/SetMenu/SetText.c \
  firmware/rockchip/ui/USB/FunUSB.c \
  firmware/rockchip/ui/USB/FunUSBInterface.c \
  firmware/rockchip/ui/CharegeWin/ChargeWin.c \
  firmware/rockchip/ui/SetMenu/SetBright.c \
  firmware/rockchip/ui/PicWin/PicInterface.c \
  firmware/rockchip/ui/PicWin/PicWin.c \
  firmware/rockchip/ui/MusicWin/MusicLrc.c \
  firmware/rockchip/ui/TextWin/TextBookmark.c \
  firmware/rockchip/ui/TextWin/TextInterface.c \
  firmware/rockchip/ui/TextWin/TextWin.c \
  firmware/rockchip/ui/VideoWin/videowin.c \
  firmware/rockchip/ui/VideoWin/VideoWinInterface.c \
  firmware/rockchip/ui/SetMenu/BluetoothDevInfoWin.c \
  firmware/rockchip/ui/SetMenu/BluetoothScanWin.c \
  firmware/rockchip/ui/SetMenu/SetBluetooth.c \
  firmware/rockchip/ui/SetMenu/BluetoothPinCodeWin.c \
  firmware/rockchip/driver/USB/device/storage.c \
  firmware/rockchip/driver/USB/device/USBDevice.c \
  firmware/rockchip/driver/USB/device/USBIsr.c \
  firmware/rockchip/driver/USB/device/USBSerial.c \
  firmware/rockchip/driver/USB/USBComm.c \
  firmware/rockchip/audio/AudioControl/AudioControl.c \
  firmware/rockchip/audio/AudioControl/HoldonPlay.c \
  firmware/rockchip/audio/Common/audio_file_access.c \
  firmware/rockchip/audio/Common/audio_track_control.c \
  firmware/rockchip/audio/Common/pCODECS.c \
  firmware/rockchip/ui/medialib/MediaBroWin.c \
  firmware/rockchip/ui/medialib/medialibwin.c \
  firmware/rockchip/sortfileinfo/FavoOperate.c \
  firmware/rockchip/sortfileinfo/FavoReset.c \
  firmware/rockchip/sortfileinfo/FileInfoSave.c \
  firmware/rockchip/sortfileinfo/SortInfoGet.c \
  firmware/rockchip/sortfileinfo/FileInfoSort.c \
  firmware/rockchip/ui/medialib/MDBBuildWin.c \
  firmware/rockchip/system/sysservice/bb_core.c

# Enabled Keil A_CORE sources not imported under firmware/rockchip.
AP_MISSING_SRCS := \
  community/sdks/RKNanoD_MP3_V1.3_20161102/SDK_160_128/Scatter/ScatterLoader.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/BootLoader/Start.s \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/BootLoader/Cortex-m3.S \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/VideoControl/VideoControl.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/VideoControl/VideoHoldonPlay.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/Avi/xvid_dec_main.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/Avi/AviFile/avi_file_access.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/Avi/AviFile/AviFile.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/mp2/pMP2.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/mp2/pMp2Codec.c \
  community/sdks/RKNanoD_MP3_V1.3_20161102/Common/Codec/Video/mp2/Video_AudioControl.c

# Existing imported directories mapped from the Keil RkNano A_CORE include path.
AP_INCLUDE_DIRS := \
  firmware/rockchip/system/os \
  firmware/rockchip/system/module_overlay \
  firmware/rockchip/system/sysservice \
  firmware/rockchip/system/fileseek \
  firmware/rockchip/driver \
  firmware/rockchip/driver/NVIC \
  firmware/rockchip/driver/ADC \
  firmware/rockchip/driver/DMA \
  firmware/rockchip/driver/PWM \
  firmware/rockchip/driver/I2C \
  firmware/rockchip/driver/IIS \
  firmware/rockchip/driver/CRU \
  firmware/rockchip/driver/PMU \
  firmware/rockchip/driver/GPIO \
  firmware/rockchip/driver/SPI \
  firmware/rockchip/driver/TIMER \
  firmware/rockchip/driver/SYSTICK \
  firmware/rockchip/driver/SDMMC \
  firmware/rockchip/driver/LCD \
  firmware/rockchip/driver/AD_KEY \
  firmware/rockchip/driver/DAC \
  firmware/rockchip/driver/DAC/rockcodec \
  firmware/rockchip/driver/DAC/wm8987 \
  firmware/rockchip/driver/RadioDriver/FM5767 \
  firmware/rockchip/filesys \
  firmware/rockchip/display \
  firmware/rockchip/ui/dialog \
  firmware/rockchip/ui/MainMenu \
  firmware/rockchip/ui/MusicWin \
  firmware/rockchip/ui/RadioWin \
  firmware/rockchip/ui/PicWin \
  firmware/rockchip/ui/RadioWin/RadioSubWin \
  firmware/rockchip/ui/RecordWin \
  firmware/rockchip/ui/TextWin \
  firmware/rockchip/ui/Browser/BroCore \
  firmware/rockchip/ui/Browser/BrowserUI \
  firmware/rockchip/ui/SetMenu \
  firmware/rockchip/ui/USB \
  firmware/rockchip/audio/AudioControl \
  firmware/rockchip/audio/Include \
  firmware/rockchip/audio/Mp3 \
  firmware/rockchip/audio/Spectrum \
  firmware/rockchip/audio/RkEQ \
  firmware/rockchip/audio/RkEQ/Effect \
  firmware/rockchip/audio/RecordControl \
  firmware/rockchip/audio/Wav \
  firmware/rockchip/audio/Wav/WAV_LIB \
  firmware/rockchip/ui/VideoWin \
  firmware/rockchip/audio/ID3 \
  firmware/rockchip/sortfileinfo \
  firmware/rockchip/ui/medialib \
  firmware/rockchip/driver/UART \
  firmware/rockchip/driver/IMDCT36_SYNTH \
  firmware/rockchip/audio/ShuffleAll \
  firmware/rockchip/driver/USB \
  firmware/rockchip/driver/USB/device \
  firmware/rockchip/driver/MemDev \
  firmware/rockchip/ui/CharegeWin \
  firmware/rockchip/driver/MemDev/SD_MMC \
  firmware/rockchip/audio/RecordControl/NS \
  firmware/rockchip/fwupdate \
  firmware/rockchip \
  firmware/rockchip/driver/vop \
  firmware/rockchip/driver/mailbox \
  firmware/rockchip/driver/GRF \
  firmware/rockchip/driver/WatchDog \
  firmware/rockchip/driver/PVTM \
  firmware/rockchip/driver/DAC/ALC5633 \
  firmware/rockchip/driver/pmc \
  firmware/rockchip/plug/uartdevice \
  firmware/rockchip/plug/bsp \
  firmware/rockchip/plug/shell \
  firmware/rockchip/bbsystem \
  firmware/rockchip/audio/AAC \
  firmware/rockchip/audio/Ogg \
  firmware/rockchip/audio/HIFI/ape \
  firmware/rockchip/audio/HIFI/alac \
  firmware/rockchip/audio/HIFI/flac \
  firmware/rockchip/driver/BB \
  firmware/rockchip/plug/spidevice \
  firmware/rockchip/audio/SSRC/resampler \
  firmware/rockchip/audio/SSRC \
  firmware/rockchip/audio/sbc/sbc_encode \
  firmware/rockchip/audio/DSF \
  firmware/rockchip/audio/DSDIFF \
  firmware/rockchip/driver/USB/host \
  firmware/rockchip/radio/FMControl \
  firmware/rockchip/image/ImageInclude \
  firmware/rockchip/image/Imagecontrol \
  firmware/rockchip/image/ImageCommon \
  firmware/rockchip/image/Thumbnail \
  firmware/rockchip/image/Jpg \
  firmware/rockchip/image/Bmp \
  firmware/rockchip/bt \
  firmware/rockchip/bt/lwbt \
  firmware/rockchip/bt/lwbt/a2dp_source \
  firmware/rockchip/bt/lwbt/chipset_rtk8761a \
  firmware/rockchip/usbcontrol \
  firmware/rockchip/include
